#!/bin/bash

COMMIT_REGEX="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z ]+\))?: .{10}"
error_msg="Invalid commit message \"$(head -n 1 $1)\". Pattern: \"$COMMIT_REGEX\".\n"

if ! grep -iqE "$COMMIT_REGEX" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
